functions:
- getTechRecords:
    method: GET
    path: /vehicles/{+proxy}/tech-records/
    proxy: :searchIdentifier
    function: getTechRecords
- postTechRecords:
    method: POST
    path: /vehicles
    function: postTechRecords
- updateTechRecords:
    method: PUT
    path: /vehicles/:systemNumber
    function: updateTechRecords
- updateTechRecordStatus:
    method: PUT
    path: /vehicles/update-status/:systemNumber
    function: updateTechRecordStatus
- updateEuVehicleCategory:
    method: PUT
    path: /vehicles/update-eu-vehicle-category/:systemNumber
    function: updateEuVehicleCategory
- addProvisionalTechRecord:
    method: POST
    path: /vehicles/add-provisional/:systemNumber
    proxy: :systemNumber
    function: addProvisionalTechRecord
- archiveTechRecordStatus:
    method: PUT
    path: /vehicles/archive/:systemNumber
    proxy: :systemNumber
    function: archiveTechRecordStatus
- updateVin:
    method: PUT
    path: /vehicles/update-vin/:systemNumber
    function: updateVin

dynamodb:
  local:
    params:
      region: localhost
      endpoint: http://localhost:8003
      convertEmptyValues: true
    table: cvs-local-technical-records
  local-global:
    params:
      region: localhost
      endpoint: http://localhost:8000
      convertEmptyValues: true
    table: cvs-local-global-technical-records
  remote:
    params:
      convertEmptyValues: true
    table: cvs-${BRANCH}-technical-records
serverless:
  basePath: /${BRANCH}
  port: 3005
endpoints:
  local:
    params:
      apiVersion: '2015-03-31'
      region: eu-west-1
      endpoint: http://localhost:3008
    functions:
      numberGenerationService:
        name: cvs-svc-test-number-dev-generateTestNumber
  remote:
    params:
      apiVersion: '2015-03-31'
    functions:
      numberGenerationService:
        name: test-number-${BRANCH}
allowAdrUpdatesOnly: false
