name: Continuous Integration
on:
  push:
    paths-ignore:
      - .github/**
      - manifest.json

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  security:
    uses: dvsa/.github/.github/workflows/nodejs-security.yaml@v2
    with:
      args: '--all-projects'
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
