# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ☑ PR Checks
on:
  push:
    branches:
      - develop
    paths-ignore:
      - .github/**
      - manifest.json
  pull_request:
    branches:
      - develop
    paths-ignore:
      - .github/**
      - manifest.json

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write

jobs:
  build-and-push:
    name: 🧱 Build and Push
    uses: ./.github/workflows/build-and-push.yaml

  scanner:
    name: SonarQube Scan
    runs-on: [self-hosted, X64, macOS]
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Get Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CVS_MGMT_AWS_ROLE }}
          aws-region: ${{ secrets.DVSA_AWS_REGION }}
          role-session-name: GHA_SonarQube
      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: sonarqube-gha
          parse-json-secrets: true
      - name: Install dependencies
        run: npm ci
      - name: Run SonarQube scanner
        run: |
          npm run test && \
          npm run sonar-scanner -- \
          -Dsonar.host.url=${{ env.SONARQUBE_GHA_URL }} \
          -Dsonar.token=${{ env.SONARQUBE_GHA_TOKEN }} \
          -Dsonar.login=${{ env.SONARQUBE_GHA_TOKEN }} \
          -Dsonar.projectName=${{ github.repository }} \
          -Dsonar.projectVersion=1.0.${{ github.run_id }}